#pragma checksum "..\..\..\..\AreaVisualizer\Gui.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "34DA9417388742DB61893EDCA27FE12F33B03C7C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HelixToolkit.Wpf;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Legacy.AreaVisualizer {
    
    
    /// <summary>
    /// Gui
    /// </summary>
    public partial class Gui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 11 "..\..\..\..\AreaVisualizer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HelixToolkit.Wpf.HelixViewport3D HelixView;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\AreaVisualizer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ReloadExilePatherButton;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\AreaVisualizer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RefreshButton;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\AreaVisualizer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox LockCameraToPlayer;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\AreaVisualizer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ShowLocalPlayer;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\AreaVisualizer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ShowNavMesh;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\AreaVisualizer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ShowNavGrid;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\AreaVisualizer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PlayerLocationText;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\AreaVisualizer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CameraPositionText;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\AreaVisualizer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CameraLookDirectionText;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\AreaVisualizer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PathfindX;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\AreaVisualizer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PathfindY;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\..\AreaVisualizer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PathfindWallDistance;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Legacy;component/areavisualizer/gui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\AreaVisualizer\Gui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.HelixView = ((HelixToolkit.Wpf.HelixViewport3D)(target));
            return;
            case 2:
            this.ReloadExilePatherButton = ((System.Windows.Controls.Button)(target));
            
            #line 29 "..\..\..\..\AreaVisualizer\Gui.xaml"
            this.ReloadExilePatherButton.Click += new System.Windows.RoutedEventHandler(this.ReloadExilePatherButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 3:
            this.RefreshButton = ((System.Windows.Controls.Button)(target));
            
            #line 31 "..\..\..\..\AreaVisualizer\Gui.xaml"
            this.RefreshButton.Click += new System.Windows.RoutedEventHandler(this.RefreshButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 4:
            this.LockCameraToPlayer = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 5:
            this.ShowLocalPlayer = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 6:
            this.ShowNavMesh = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.ShowNavGrid = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 8:
            this.PlayerLocationText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.CameraPositionText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.CameraLookDirectionText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.PathfindX = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.PathfindY = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.PathfindWallDistance = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

