#pragma checksum "..\..\..\..\AutoLogin\Gui.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6C182C035BB3BC1A48EE9044C7DD230EFFF89C63"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Exilebuddy;
using Legacy.AutoLogin;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Legacy.AutoLogin {
    
    
    /// <summary>
    /// Gui
    /// </summary>
    public partial class Gui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 39 "..\..\..\..\AutoLogin\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxAutoLogin;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\AutoLogin\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxLoginUsingUserCredentials;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\AutoLogin\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxLoginUsingGateway;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\..\..\AutoLogin\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox GatewayComboBox;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\AutoLogin\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxDelayBeforeLoginAttempt;
        
        #line default
        #line hidden
        
        
        #line 139 "..\..\..\..\AutoLogin\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxAutoSelectCharacter;
        
        #line default
        #line hidden
        
        
        #line 165 "..\..\..\..\AutoLogin\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CharactersComboBox;
        
        #line default
        #line hidden
        
        
        #line 166 "..\..\..\..\AutoLogin\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button LoadCharactersButton;
        
        #line default
        #line hidden
        
        
        #line 196 "..\..\..\..\AutoLogin\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxDelayBeforeSelectingCharacter;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Legacy;component/autologin/gui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\AutoLogin\Gui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.CheckBoxAutoLogin = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 2:
            this.CheckBoxLoginUsingUserCredentials = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 3:
            this.CheckBoxLoginUsingGateway = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 4:
            this.GatewayComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 95 "..\..\..\..\AutoLogin\Gui.xaml"
            this.GatewayComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.GatewayComboBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.CheckBoxDelayBeforeLoginAttempt = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 6:
            this.CheckBoxAutoSelectCharacter = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.CharactersComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 165 "..\..\..\..\AutoLogin\Gui.xaml"
            this.CharactersComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CharactersComboBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.LoadCharactersButton = ((System.Windows.Controls.Button)(target));
            
            #line 166 "..\..\..\..\AutoLogin\Gui.xaml"
            this.LoadCharactersButton.Click += new System.Windows.RoutedEventHandler(this.LoadCharactersButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 9:
            this.CheckBoxDelayBeforeSelectingCharacter = ((System.Windows.Controls.CheckBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

