#pragma checksum "..\..\..\..\GemLeveler\Gui.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4BF4FA44B7DE4BCF3D083EFDCE1E1013CB999A6D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Legacy.GemLeveler;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Legacy.GemLeveler {
    
    
    /// <summary>
    /// Gui
    /// </summary>
    public partial class Gui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 24 "..\..\..\..\GemLeveler\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox DebugStatementsCheckBox;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\GemLeveler\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RefreshSkillsButton;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\GemLeveler\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox GlobalNameIgnoreTextBox;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\GemLeveler\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddGlobalNameIgnoreButton;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\GemLeveler\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RemoveGlobalNameIgnoreButton;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\..\GemLeveler\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox GlobalNameIgnoreListListBox;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\GemLeveler\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox AllSkillGemsComboBox;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\..\GemLeveler\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddSkillGemButton;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\..\..\GemLeveler\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RemoveSkillGemButton;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\..\..\GemLeveler\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddAllSkillGemButton;
        
        #line default
        #line hidden
        
        
        #line 110 "..\..\..\..\GemLeveler\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RemoveAllSkillGemButton;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\..\..\GemLeveler\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox SkillGemsToLevelListListBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Legacy;component/gemleveler/gui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\GemLeveler\Gui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.DebugStatementsCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 2:
            this.RefreshSkillsButton = ((System.Windows.Controls.Button)(target));
            
            #line 41 "..\..\..\..\GemLeveler\Gui.xaml"
            this.RefreshSkillsButton.Click += new System.Windows.RoutedEventHandler(this.RefreshSkillsButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 3:
            this.GlobalNameIgnoreTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.AddGlobalNameIgnoreButton = ((System.Windows.Controls.Button)(target));
            
            #line 61 "..\..\..\..\GemLeveler\Gui.xaml"
            this.AddGlobalNameIgnoreButton.Click += new System.Windows.RoutedEventHandler(this.AddGlobalNameIgnoreButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 5:
            this.RemoveGlobalNameIgnoreButton = ((System.Windows.Controls.Button)(target));
            
            #line 64 "..\..\..\..\GemLeveler\Gui.xaml"
            this.RemoveGlobalNameIgnoreButton.Click += new System.Windows.RoutedEventHandler(this.RemoveGlobalNameIgnoreButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.GlobalNameIgnoreListListBox = ((System.Windows.Controls.ListBox)(target));
            return;
            case 7:
            this.AllSkillGemsComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 8:
            this.AddSkillGemButton = ((System.Windows.Controls.Button)(target));
            
            #line 103 "..\..\..\..\GemLeveler\Gui.xaml"
            this.AddSkillGemButton.Click += new System.Windows.RoutedEventHandler(this.AddSkillGemButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 9:
            this.RemoveSkillGemButton = ((System.Windows.Controls.Button)(target));
            
            #line 106 "..\..\..\..\GemLeveler\Gui.xaml"
            this.RemoveSkillGemButton.Click += new System.Windows.RoutedEventHandler(this.RemoveSkillGemButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 10:
            this.AddAllSkillGemButton = ((System.Windows.Controls.Button)(target));
            
            #line 109 "..\..\..\..\GemLeveler\Gui.xaml"
            this.AddAllSkillGemButton.Click += new System.Windows.RoutedEventHandler(this.AddAllSkillGemButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 11:
            this.RemoveAllSkillGemButton = ((System.Windows.Controls.Button)(target));
            
            #line 112 "..\..\..\..\GemLeveler\Gui.xaml"
            this.RemoveAllSkillGemButton.Click += new System.Windows.RoutedEventHandler(this.RemoveAllSkillGemButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 12:
            this.SkillGemsToLevelListListBox = ((System.Windows.Controls.ListBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

