#pragma checksum "..\..\..\..\MapBot\Gui.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "2188EC40656C75825C5BB16034D5F8EA6595FD66"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Default.MapBot;
using MahApps.Metro.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Default.MapBot {
    
    
    /// <summary>
    /// Gui
    /// </summary>
    public partial class Gui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 120 "..\..\..\..\MapBot\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox SellEnabledCheckBox;
        
        #line default
        #line hidden
        
        
        #line 291 "..\..\..\..\MapBot\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox AtlasExploreCheckbox;
        
        #line default
        #line hidden
        
        
        #line 639 "..\..\..\..\MapBot\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MapSearchTextBox;
        
        #line default
        #line hidden
        
        
        #line 646 "..\..\..\..\MapBot\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid MapGrid;
        
        #line default
        #line hidden
        
        
        #line 803 "..\..\..\..\MapBot\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AffixSearchTextBox;
        
        #line default
        #line hidden
        
        
        #line 810 "..\..\..\..\MapBot\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid AffixGrid;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Default;component/mapbot/gui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\MapBot\Gui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SellEnabledCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 2:
            this.AtlasExploreCheckbox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 3:
            this.MapSearchTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 643 "..\..\..\..\MapBot\Gui.xaml"
            this.MapSearchTextBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.MapSearchTextBox_TextChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.MapGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 650 "..\..\..\..\MapBot\Gui.xaml"
            this.MapGrid.BeginningEdit += new System.EventHandler<System.Windows.Controls.DataGridBeginningEditEventArgs>(this.MapGrid_BeginningEdit);
            
            #line default
            #line hidden
            
            #line 656 "..\..\..\..\MapBot\Gui.xaml"
            this.MapGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.DataGridUnselectAll);
            
            #line default
            #line hidden
            return;
            case 7:
            this.AffixSearchTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 807 "..\..\..\..\MapBot\Gui.xaml"
            this.AffixSearchTextBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.AffixSearchTextBox_TextChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.AffixGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 819 "..\..\..\..\MapBot\Gui.xaml"
            this.AffixGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.DataGridUnselectAll);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            System.Windows.EventSetter eventSetter;
            switch (connectionId)
            {
            case 5:
            eventSetter = new System.Windows.EventSetter();
            eventSetter.Event = System.Windows.Controls.Primitives.ButtonBase.ClickEvent;
            
            #line 687 "..\..\..\..\MapBot\Gui.xaml"
            eventSetter.Handler = new System.Windows.RoutedEventHandler(this.OnIbCheckBoxClicked);
            
            #line default
            #line hidden
            ((System.Windows.Style)(target)).Setters.Add(eventSetter);
            break;
            case 6:
            eventSetter = new System.Windows.EventSetter();
            eventSetter.Event = System.Windows.Controls.Primitives.ButtonBase.ClickEvent;
            
            #line 775 "..\..\..\..\MapBot\Gui.xaml"
            eventSetter.Handler = new System.Windows.RoutedEventHandler(this.OnFtCheckBoxClicked);
            
            #line default
            #line hidden
            ((System.Windows.Style)(target)).Setters.Add(eventSetter);
            break;
            }
        }
    }
}

