#pragma checksum "..\..\..\..\EXtensions\Gui.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6B3160A3FD5A9E55B618D25711609CFF7A59EBF5"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Default.EXtensions;
using MahApps.Metro.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Default.EXtensions {
    
    
    /// <summary>
    /// Gui
    /// </summary>
    public partial class Gui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 440 "..\..\..\..\EXtensions\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CardsEnabledCheckbox;
        
        #line default
        #line hidden
        
        
        #line 491 "..\..\..\..\EXtensions\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox GcpEnabledCheckbox;
        
        #line default
        #line hidden
        
        
        #line 677 "..\..\..\..\EXtensions\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox SdEnabledCheckbox;
        
        #line default
        #line hidden
        
        
        #line 777 "..\..\..\..\EXtensions\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox DelaysCheckBox;
        
        #line default
        #line hidden
        
        
        #line 788 "..\..\..\..\EXtensions\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MahApps.Metro.Controls.RangeSlider DelaysBounds;
        
        #line default
        #line hidden
        
        
        #line 828 "..\..\..\..\EXtensions\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid InventoryCurrencyGrid;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Default;component/extensions/gui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\EXtensions\Gui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.CardsEnabledCheckbox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 2:
            this.GcpEnabledCheckbox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 3:
            this.SdEnabledCheckbox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 4:
            this.DelaysCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 5:
            this.DelaysBounds = ((MahApps.Metro.Controls.RangeSlider)(target));
            return;
            case 6:
            this.InventoryCurrencyGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 7:
            
            #line 839 "..\..\..\..\EXtensions\Gui.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.InventoryCurrencyAdd);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 840 "..\..\..\..\EXtensions\Gui.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.InventoryCurrencyDelete);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

