#pragma checksum "..\..\..\..\DumpTab\Gui.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6086A14EF2283B875376789703FFFACE004EC25B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Legacy.DumpTab;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Legacy.DumpTab {
    
    
    /// <summary>
    /// Gui
    /// </summary>
    public partial class Gui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpQuestRewards;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpWorldAreas;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpStats;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpQuestStates;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpQuests;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpProphecies;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpPassiveSkills;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpNpcTalk;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpNpcs;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpMonsterVarieties;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpMods;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpMinimapIcons;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpGrantedEffectsPerLevel;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpGrantedEffects;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpClientStrings;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpChests;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpBuffDefinitions;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpBaseItemTypes;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpBackendErrors;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpActiveSkills;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpTerrainData;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpInstanceInfo;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugInstanceInfo;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpLocalData;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpLabyrinthData;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpStates;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSaveInstanceInfoToFile;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSaveLocalDataToFile;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSavePlayerToFile;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSaveUiDataToFile;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpPantheonPanelLayout;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpWords;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpFlavourText;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpLabyrinthTrials;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpSkillGems;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpItemExperiencePerLevel;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpSkillData;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSavePlayerSkillDataToFile;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpBestiaryCapturableMonsters;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpBestiaryGenus;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpBestiaryGroups;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpBestiaryFamilies;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpBestiaryEncounters;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpBestiaryNets;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpBestiaryRecipeComponent;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpBestiaryRecipeItemCreation;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpBestiaryRecipes;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpIncursionRooms;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDumpIncursionArchitect;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGenerateStatType;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGenerateClientStrings;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGenerateBuffDefinitions;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGenerateBaseItemTypesComposite;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGenerateBaseItemTypes;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGenerateBackendErrors;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGenerateActiveSkills;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGenerateItemClasses;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGenerate;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGenerateCurrencyStashTabLayoutCode;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGenerateDivinationCardStashTabLayoutCode;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGenerateEssenceStashTabLayoutCode;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGenerateFragmentStashTabLayoutCode;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonGenerateKnownNames;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugWorldPanel;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugTrialPlaqueUi;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugTradeUi;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugTimerHud;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugStoneAltarUi;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugSplitStackUi;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugSocialUi;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugSkillsUi;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugSkillGemHud;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugSkillBarHud;
        
        #line default
        #line hidden
        
        
        #line 106 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugSellUi;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugSacrificeUi;
        
        #line default
        #line hidden
        
        
        #line 108 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugRewardUi;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugResurrectPanel;
        
        #line default
        #line hidden
        
        
        #line 110 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugQuickFlaskHud;
        
        #line default
        #line hidden
        
        
        #line 111 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugQuestTrackerOverlay;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugPurchaseUi;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugPartyHud;
        
        #line default
        #line hidden
        
        
        #line 114 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugNpcDialogUi;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugNotificationHud;
        
        #line default
        #line hidden
        
        
        #line 116 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugMasterDeviceUi;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugMapDeviceUi;
        
        #line default
        #line hidden
        
        
        #line 118 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugLabyrinthMapUi;
        
        #line default
        #line hidden
        
        
        #line 119 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugLabyrinthMapSelectorUi;
        
        #line default
        #line hidden
        
        
        #line 120 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugInventoryUi;
        
        #line default
        #line hidden
        
        
        #line 121 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugInstanceManagerUi;
        
        #line default
        #line hidden
        
        
        #line 122 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugGuildStashUi;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugGlobalWarningDialog;
        
        #line default
        #line hidden
        
        
        #line 124 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugDisplayNoteUi;
        
        #line default
        #line hidden
        
        
        #line 125 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugDebugOverlay;
        
        #line default
        #line hidden
        
        
        #line 126 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugCursorItemOverlay;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugContextMenu;
        
        #line default
        #line hidden
        
        
        #line 128 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugChatPanel;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugChallengesUi;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugCardTradeUi;
        
        #line default
        #line hidden
        
        
        #line 131 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugCadiroOfferUi;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugBanditPanel;
        
        #line default
        #line hidden
        
        
        #line 133 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugAtlasUi;
        
        #line default
        #line hidden
        
        
        #line 134 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugAscendancySelectionUi;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugDivineFont;
        
        #line default
        #line hidden
        
        
        #line 136 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugPantheon;
        
        #line default
        #line hidden
        
        
        #line 144 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugTutorialUi;
        
        #line default
        #line hidden
        
        
        #line 145 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugEssenceTab;
        
        #line default
        #line hidden
        
        
        #line 146 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugDivinationTab;
        
        #line default
        #line hidden
        
        
        #line 147 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugCurrencyTab;
        
        #line default
        #line hidden
        
        
        #line 148 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugStashUi;
        
        #line default
        #line hidden
        
        
        #line 149 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugFragmentTab;
        
        #line default
        #line hidden
        
        
        #line 150 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugProphecyPopupUi;
        
        #line default
        #line hidden
        
        
        #line 151 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugBestiary;
        
        #line default
        #line hidden
        
        
        #line 152 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugShopUi;
        
        #line default
        #line hidden
        
        
        #line 153 "..\..\..\..\DumpTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonDebugIncursion;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Legacy;component/dumptab/gui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\DumpTab\Gui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ButtonDumpQuestRewards = ((System.Windows.Controls.Button)(target));
            
            #line 13 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpQuestRewards.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpQuestRewards_OnClick);
            
            #line default
            #line hidden
            return;
            case 2:
            this.ButtonDumpWorldAreas = ((System.Windows.Controls.Button)(target));
            
            #line 14 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpWorldAreas.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpWorldAreas_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.ButtonDumpStats = ((System.Windows.Controls.Button)(target));
            
            #line 15 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpStats.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpStats_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.ButtonDumpQuestStates = ((System.Windows.Controls.Button)(target));
            
            #line 16 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpQuestStates.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpQuestStates_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ButtonDumpQuests = ((System.Windows.Controls.Button)(target));
            
            #line 17 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpQuests.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpQuests_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.ButtonDumpProphecies = ((System.Windows.Controls.Button)(target));
            
            #line 18 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpProphecies.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpProphecies_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.ButtonDumpPassiveSkills = ((System.Windows.Controls.Button)(target));
            
            #line 19 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpPassiveSkills.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpPassiveSkills_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ButtonDumpNpcTalk = ((System.Windows.Controls.Button)(target));
            
            #line 20 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpNpcTalk.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpNpcTalk_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.ButtonDumpNpcs = ((System.Windows.Controls.Button)(target));
            
            #line 21 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpNpcs.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpNpcs_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.ButtonDumpMonsterVarieties = ((System.Windows.Controls.Button)(target));
            
            #line 22 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpMonsterVarieties.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpMonsterVarieties_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.ButtonDumpMods = ((System.Windows.Controls.Button)(target));
            
            #line 23 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpMods.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpMods_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.ButtonDumpMinimapIcons = ((System.Windows.Controls.Button)(target));
            
            #line 24 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpMinimapIcons.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpMinimapIcons_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.ButtonDumpGrantedEffectsPerLevel = ((System.Windows.Controls.Button)(target));
            
            #line 25 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpGrantedEffectsPerLevel.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpGrantedEffectsPerLevel_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.ButtonDumpGrantedEffects = ((System.Windows.Controls.Button)(target));
            
            #line 26 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpGrantedEffects.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpGrantedEffects_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.ButtonDumpClientStrings = ((System.Windows.Controls.Button)(target));
            
            #line 27 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpClientStrings.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpClientStrings_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.ButtonDumpChests = ((System.Windows.Controls.Button)(target));
            
            #line 28 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpChests.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpChests_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.ButtonDumpBuffDefinitions = ((System.Windows.Controls.Button)(target));
            
            #line 29 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpBuffDefinitions.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpBuffDefinitions_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.ButtonDumpBaseItemTypes = ((System.Windows.Controls.Button)(target));
            
            #line 30 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpBaseItemTypes.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpBaseItemTypes_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.ButtonDumpBackendErrors = ((System.Windows.Controls.Button)(target));
            
            #line 31 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpBackendErrors.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpBackendErrors_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.ButtonDumpActiveSkills = ((System.Windows.Controls.Button)(target));
            
            #line 32 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpActiveSkills.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpActiveSkills_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.ButtonDumpTerrainData = ((System.Windows.Controls.Button)(target));
            
            #line 33 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpTerrainData.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpTerrainData_OnClick);
            
            #line default
            #line hidden
            return;
            case 22:
            this.ButtonDumpInstanceInfo = ((System.Windows.Controls.Button)(target));
            
            #line 34 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpInstanceInfo.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpInstanceInfo_OnClick);
            
            #line default
            #line hidden
            return;
            case 23:
            this.ButtonDebugInstanceInfo = ((System.Windows.Controls.Button)(target));
            
            #line 35 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugInstanceInfo.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugInstanceInfo_OnClick);
            
            #line default
            #line hidden
            return;
            case 24:
            this.ButtonDumpLocalData = ((System.Windows.Controls.Button)(target));
            
            #line 36 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpLocalData.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpLocalData_OnClick);
            
            #line default
            #line hidden
            return;
            case 25:
            this.ButtonDumpLabyrinthData = ((System.Windows.Controls.Button)(target));
            
            #line 37 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpLabyrinthData.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpLabyrinthData_OnClick);
            
            #line default
            #line hidden
            return;
            case 26:
            this.ButtonDumpStates = ((System.Windows.Controls.Button)(target));
            
            #line 38 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpStates.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpStates_OnClick);
            
            #line default
            #line hidden
            return;
            case 27:
            this.ButtonSaveInstanceInfoToFile = ((System.Windows.Controls.Button)(target));
            
            #line 40 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonSaveInstanceInfoToFile.Click += new System.Windows.RoutedEventHandler(this.ButtonSaveInstanceInfoToFile_OnClick);
            
            #line default
            #line hidden
            return;
            case 28:
            this.ButtonSaveLocalDataToFile = ((System.Windows.Controls.Button)(target));
            
            #line 41 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonSaveLocalDataToFile.Click += new System.Windows.RoutedEventHandler(this.ButtonSaveLocalDataToFile_OnClick);
            
            #line default
            #line hidden
            return;
            case 29:
            this.ButtonSavePlayerToFile = ((System.Windows.Controls.Button)(target));
            
            #line 42 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonSavePlayerToFile.Click += new System.Windows.RoutedEventHandler(this.ButtonSavePlayerToFile_OnClick);
            
            #line default
            #line hidden
            return;
            case 30:
            this.ButtonSaveUiDataToFile = ((System.Windows.Controls.Button)(target));
            
            #line 43 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonSaveUiDataToFile.Click += new System.Windows.RoutedEventHandler(this.ButtonSaveUiDataToFile_Click);
            
            #line default
            #line hidden
            return;
            case 31:
            this.ButtonDumpPantheonPanelLayout = ((System.Windows.Controls.Button)(target));
            
            #line 45 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpPantheonPanelLayout.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpPPantheonPanelLayout_OnClick);
            
            #line default
            #line hidden
            return;
            case 32:
            this.ButtonDumpWords = ((System.Windows.Controls.Button)(target));
            
            #line 46 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpWords.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpWords_OnClick);
            
            #line default
            #line hidden
            return;
            case 33:
            this.ButtonDumpFlavourText = ((System.Windows.Controls.Button)(target));
            
            #line 47 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpFlavourText.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpFlavourText_OnClick);
            
            #line default
            #line hidden
            return;
            case 34:
            this.ButtonDumpLabyrinthTrials = ((System.Windows.Controls.Button)(target));
            
            #line 48 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpLabyrinthTrials.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpLabyrinthTrials_OnClick);
            
            #line default
            #line hidden
            return;
            case 35:
            this.ButtonDumpSkillGems = ((System.Windows.Controls.Button)(target));
            
            #line 49 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpSkillGems.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpSkillGems_Click);
            
            #line default
            #line hidden
            return;
            case 36:
            this.ButtonDumpItemExperiencePerLevel = ((System.Windows.Controls.Button)(target));
            
            #line 50 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpItemExperiencePerLevel.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpItemExperiencePerLevel_Click);
            
            #line default
            #line hidden
            return;
            case 37:
            this.ButtonDumpSkillData = ((System.Windows.Controls.Button)(target));
            
            #line 51 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpSkillData.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpSkillData_Click);
            
            #line default
            #line hidden
            return;
            case 38:
            this.ButtonSavePlayerSkillDataToFile = ((System.Windows.Controls.Button)(target));
            
            #line 52 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonSavePlayerSkillDataToFile.Click += new System.Windows.RoutedEventHandler(this.ButtonSavePlayerSkillDataToFile_Click);
            
            #line default
            #line hidden
            return;
            case 39:
            this.ButtonDumpBestiaryCapturableMonsters = ((System.Windows.Controls.Button)(target));
            
            #line 59 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpBestiaryCapturableMonsters.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpBestiaryCapturableMonsters_Click);
            
            #line default
            #line hidden
            return;
            case 40:
            this.ButtonDumpBestiaryGenus = ((System.Windows.Controls.Button)(target));
            
            #line 60 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpBestiaryGenus.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpBestiaryGenus_Click);
            
            #line default
            #line hidden
            return;
            case 41:
            this.ButtonDumpBestiaryGroups = ((System.Windows.Controls.Button)(target));
            
            #line 61 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpBestiaryGroups.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpBestiaryGroups_Click);
            
            #line default
            #line hidden
            return;
            case 42:
            this.ButtonDumpBestiaryFamilies = ((System.Windows.Controls.Button)(target));
            
            #line 62 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpBestiaryFamilies.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpBestiaryFamilies_Click);
            
            #line default
            #line hidden
            return;
            case 43:
            this.ButtonDumpBestiaryEncounters = ((System.Windows.Controls.Button)(target));
            
            #line 63 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpBestiaryEncounters.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpBestiaryEncounters_Click);
            
            #line default
            #line hidden
            return;
            case 44:
            this.ButtonDumpBestiaryNets = ((System.Windows.Controls.Button)(target));
            
            #line 64 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpBestiaryNets.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpBestiaryNets_Click);
            
            #line default
            #line hidden
            return;
            case 45:
            this.ButtonDumpBestiaryRecipeComponent = ((System.Windows.Controls.Button)(target));
            
            #line 65 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpBestiaryRecipeComponent.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpBestiaryRecipeComponent_Click);
            
            #line default
            #line hidden
            return;
            case 46:
            this.ButtonDumpBestiaryRecipeItemCreation = ((System.Windows.Controls.Button)(target));
            
            #line 66 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpBestiaryRecipeItemCreation.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpBestiaryRecipeItemCreation_Click);
            
            #line default
            #line hidden
            return;
            case 47:
            this.ButtonDumpBestiaryRecipes = ((System.Windows.Controls.Button)(target));
            
            #line 67 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpBestiaryRecipes.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpBestiaryRecipes_Click);
            
            #line default
            #line hidden
            return;
            case 48:
            this.ButtonDumpIncursionRooms = ((System.Windows.Controls.Button)(target));
            
            #line 68 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpIncursionRooms.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpIncursionRooms_OnClick);
            
            #line default
            #line hidden
            return;
            case 49:
            this.ButtonDumpIncursionArchitect = ((System.Windows.Controls.Button)(target));
            
            #line 69 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDumpIncursionArchitect.Click += new System.Windows.RoutedEventHandler(this.ButtonDumpIncursionArchitect_OnClick);
            
            #line default
            #line hidden
            return;
            case 50:
            this.ButtonGenerateStatType = ((System.Windows.Controls.Button)(target));
            
            #line 76 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonGenerateStatType.Click += new System.Windows.RoutedEventHandler(this.ButtonGenerateStatType_OnClick);
            
            #line default
            #line hidden
            return;
            case 51:
            this.ButtonGenerateClientStrings = ((System.Windows.Controls.Button)(target));
            
            #line 77 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonGenerateClientStrings.Click += new System.Windows.RoutedEventHandler(this.ButtonGenerateClientStrings_OnClick);
            
            #line default
            #line hidden
            return;
            case 52:
            this.ButtonGenerateBuffDefinitions = ((System.Windows.Controls.Button)(target));
            
            #line 78 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonGenerateBuffDefinitions.Click += new System.Windows.RoutedEventHandler(this.ButtonGenerateBuffDefinitions_OnClick);
            
            #line default
            #line hidden
            return;
            case 53:
            this.ButtonGenerateBaseItemTypesComposite = ((System.Windows.Controls.Button)(target));
            
            #line 79 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonGenerateBaseItemTypesComposite.Click += new System.Windows.RoutedEventHandler(this.ButtonGenerateBaseItemTypesComposite_OnClick);
            
            #line default
            #line hidden
            return;
            case 54:
            this.ButtonGenerateBaseItemTypes = ((System.Windows.Controls.Button)(target));
            
            #line 80 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonGenerateBaseItemTypes.Click += new System.Windows.RoutedEventHandler(this.ButtonGenerateBaseItemTypes_OnClick);
            
            #line default
            #line hidden
            return;
            case 55:
            this.ButtonGenerateBackendErrors = ((System.Windows.Controls.Button)(target));
            
            #line 81 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonGenerateBackendErrors.Click += new System.Windows.RoutedEventHandler(this.ButtonGenerateBackendErrors_OnClick);
            
            #line default
            #line hidden
            return;
            case 56:
            this.ButtonGenerateActiveSkills = ((System.Windows.Controls.Button)(target));
            
            #line 82 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonGenerateActiveSkills.Click += new System.Windows.RoutedEventHandler(this.ButtonGenerateActiveSkills_OnClick);
            
            #line default
            #line hidden
            return;
            case 57:
            this.ButtonGenerateItemClasses = ((System.Windows.Controls.Button)(target));
            
            #line 83 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonGenerateItemClasses.Click += new System.Windows.RoutedEventHandler(this.ButtonGenerateItemClasses_OnClick);
            
            #line default
            #line hidden
            return;
            case 58:
            this.ButtonGenerate = ((System.Windows.Controls.Button)(target));
            
            #line 84 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonGenerate.Click += new System.Windows.RoutedEventHandler(this.ButtonGenerate_OnClick);
            
            #line default
            #line hidden
            return;
            case 59:
            this.ButtonGenerateCurrencyStashTabLayoutCode = ((System.Windows.Controls.Button)(target));
            
            #line 85 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonGenerateCurrencyStashTabLayoutCode.Click += new System.Windows.RoutedEventHandler(this.ButtonGenerateCurrencyStashTabLayoutCode_Click);
            
            #line default
            #line hidden
            return;
            case 60:
            this.ButtonGenerateDivinationCardStashTabLayoutCode = ((System.Windows.Controls.Button)(target));
            
            #line 86 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonGenerateDivinationCardStashTabLayoutCode.Click += new System.Windows.RoutedEventHandler(this.ButtonGenerateDivinationCardStashTabLayoutCode_Click);
            
            #line default
            #line hidden
            return;
            case 61:
            this.ButtonGenerateEssenceStashTabLayoutCode = ((System.Windows.Controls.Button)(target));
            
            #line 87 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonGenerateEssenceStashTabLayoutCode.Click += new System.Windows.RoutedEventHandler(this.ButtonGenerateEssenceStashTabLayoutCode_Click);
            
            #line default
            #line hidden
            return;
            case 62:
            this.ButtonGenerateFragmentStashTabLayoutCode = ((System.Windows.Controls.Button)(target));
            
            #line 88 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonGenerateFragmentStashTabLayoutCode.Click += new System.Windows.RoutedEventHandler(this.ButtonGenerateFragmentStashTabLayoutCode_Click);
            
            #line default
            #line hidden
            return;
            case 63:
            this.ButtonGenerateKnownNames = ((System.Windows.Controls.Button)(target));
            
            #line 89 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonGenerateKnownNames.Click += new System.Windows.RoutedEventHandler(this.ButtonGenerateKnownNames_Click);
            
            #line default
            #line hidden
            return;
            case 64:
            this.ButtonDebugWorldPanel = ((System.Windows.Controls.Button)(target));
            
            #line 96 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugWorldPanel.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugWorldPanel_OnClick);
            
            #line default
            #line hidden
            return;
            case 65:
            this.ButtonDebugTrialPlaqueUi = ((System.Windows.Controls.Button)(target));
            
            #line 97 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugTrialPlaqueUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugTrialPlaqueUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 66:
            this.ButtonDebugTradeUi = ((System.Windows.Controls.Button)(target));
            
            #line 98 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugTradeUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugTradeUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 67:
            this.ButtonDebugTimerHud = ((System.Windows.Controls.Button)(target));
            
            #line 99 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugTimerHud.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugTimerHud_OnClick);
            
            #line default
            #line hidden
            return;
            case 68:
            this.ButtonDebugStoneAltarUi = ((System.Windows.Controls.Button)(target));
            
            #line 100 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugStoneAltarUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugStoneAltarUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 69:
            this.ButtonDebugSplitStackUi = ((System.Windows.Controls.Button)(target));
            
            #line 101 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugSplitStackUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugSplitStackUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 70:
            this.ButtonDebugSocialUi = ((System.Windows.Controls.Button)(target));
            
            #line 102 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugSocialUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugSocialUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 71:
            this.ButtonDebugSkillsUi = ((System.Windows.Controls.Button)(target));
            
            #line 103 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugSkillsUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugSkillsUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 72:
            this.ButtonDebugSkillGemHud = ((System.Windows.Controls.Button)(target));
            
            #line 104 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugSkillGemHud.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugSkillGemHud_OnClick);
            
            #line default
            #line hidden
            return;
            case 73:
            this.ButtonDebugSkillBarHud = ((System.Windows.Controls.Button)(target));
            
            #line 105 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugSkillBarHud.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugSkillBarHud_OnClick);
            
            #line default
            #line hidden
            return;
            case 74:
            this.ButtonDebugSellUi = ((System.Windows.Controls.Button)(target));
            
            #line 106 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugSellUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugSellUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 75:
            this.ButtonDebugSacrificeUi = ((System.Windows.Controls.Button)(target));
            
            #line 107 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugSacrificeUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugSacrificeUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 76:
            this.ButtonDebugRewardUi = ((System.Windows.Controls.Button)(target));
            
            #line 108 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugRewardUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugRewardUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 77:
            this.ButtonDebugResurrectPanel = ((System.Windows.Controls.Button)(target));
            
            #line 109 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugResurrectPanel.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugResurrectPanel_OnClick);
            
            #line default
            #line hidden
            return;
            case 78:
            this.ButtonDebugQuickFlaskHud = ((System.Windows.Controls.Button)(target));
            
            #line 110 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugQuickFlaskHud.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugQuickFlaskHud_OnClick);
            
            #line default
            #line hidden
            return;
            case 79:
            this.ButtonDebugQuestTrackerOverlay = ((System.Windows.Controls.Button)(target));
            
            #line 111 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugQuestTrackerOverlay.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugQuestTrackerOverlay_OnClick);
            
            #line default
            #line hidden
            return;
            case 80:
            this.ButtonDebugPurchaseUi = ((System.Windows.Controls.Button)(target));
            
            #line 112 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugPurchaseUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugPurchaseUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 81:
            this.ButtonDebugPartyHud = ((System.Windows.Controls.Button)(target));
            
            #line 113 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugPartyHud.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugPartyHud_OnClick);
            
            #line default
            #line hidden
            return;
            case 82:
            this.ButtonDebugNpcDialogUi = ((System.Windows.Controls.Button)(target));
            
            #line 114 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugNpcDialogUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugNpcDialogUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 83:
            this.ButtonDebugNotificationHud = ((System.Windows.Controls.Button)(target));
            
            #line 115 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugNotificationHud.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugNotificationHud_OnClick);
            
            #line default
            #line hidden
            return;
            case 84:
            this.ButtonDebugMasterDeviceUi = ((System.Windows.Controls.Button)(target));
            
            #line 116 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugMasterDeviceUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugMasterDeviceUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 85:
            this.ButtonDebugMapDeviceUi = ((System.Windows.Controls.Button)(target));
            
            #line 117 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugMapDeviceUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugMapDeviceUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 86:
            this.ButtonDebugLabyrinthMapUi = ((System.Windows.Controls.Button)(target));
            
            #line 118 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugLabyrinthMapUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugLabyrinthMapUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 87:
            this.ButtonDebugLabyrinthMapSelectorUi = ((System.Windows.Controls.Button)(target));
            
            #line 119 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugLabyrinthMapSelectorUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugLabyrinthMapSelectorUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 88:
            this.ButtonDebugInventoryUi = ((System.Windows.Controls.Button)(target));
            
            #line 120 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugInventoryUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugInventoryUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 89:
            this.ButtonDebugInstanceManagerUi = ((System.Windows.Controls.Button)(target));
            
            #line 121 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugInstanceManagerUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugInstanceManagerUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 90:
            this.ButtonDebugGuildStashUi = ((System.Windows.Controls.Button)(target));
            
            #line 122 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugGuildStashUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugGuildStashUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 91:
            this.ButtonDebugGlobalWarningDialog = ((System.Windows.Controls.Button)(target));
            
            #line 123 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugGlobalWarningDialog.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugGlobalWarningDialog_OnClick);
            
            #line default
            #line hidden
            return;
            case 92:
            this.ButtonDebugDisplayNoteUi = ((System.Windows.Controls.Button)(target));
            
            #line 124 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugDisplayNoteUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugDisplayNoteUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 93:
            this.ButtonDebugDebugOverlay = ((System.Windows.Controls.Button)(target));
            
            #line 125 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugDebugOverlay.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugDebugOverlay_OnClick);
            
            #line default
            #line hidden
            return;
            case 94:
            this.ButtonDebugCursorItemOverlay = ((System.Windows.Controls.Button)(target));
            
            #line 126 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugCursorItemOverlay.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugCursorItemOverlay_OnClick);
            
            #line default
            #line hidden
            return;
            case 95:
            this.ButtonDebugContextMenu = ((System.Windows.Controls.Button)(target));
            
            #line 127 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugContextMenu.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugContextMenu_OnClick);
            
            #line default
            #line hidden
            return;
            case 96:
            this.ButtonDebugChatPanel = ((System.Windows.Controls.Button)(target));
            
            #line 128 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugChatPanel.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugChatPanel_OnClick);
            
            #line default
            #line hidden
            return;
            case 97:
            this.ButtonDebugChallengesUi = ((System.Windows.Controls.Button)(target));
            
            #line 129 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugChallengesUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugChallengesUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 98:
            this.ButtonDebugCardTradeUi = ((System.Windows.Controls.Button)(target));
            
            #line 130 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugCardTradeUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugCardTradeUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 99:
            this.ButtonDebugCadiroOfferUi = ((System.Windows.Controls.Button)(target));
            
            #line 131 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugCadiroOfferUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugCadiroOfferUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 100:
            this.ButtonDebugBanditPanel = ((System.Windows.Controls.Button)(target));
            
            #line 132 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugBanditPanel.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugBanditPanel_OnClick);
            
            #line default
            #line hidden
            return;
            case 101:
            this.ButtonDebugAtlasUi = ((System.Windows.Controls.Button)(target));
            
            #line 133 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugAtlasUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugAtlasUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 102:
            this.ButtonDebugAscendancySelectionUi = ((System.Windows.Controls.Button)(target));
            
            #line 134 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugAscendancySelectionUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugAscendancySelectionUi_Click);
            
            #line default
            #line hidden
            return;
            case 103:
            this.ButtonDebugDivineFont = ((System.Windows.Controls.Button)(target));
            
            #line 135 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugDivineFont.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugDivineFont_OnClick);
            
            #line default
            #line hidden
            return;
            case 104:
            this.ButtonDebugPantheon = ((System.Windows.Controls.Button)(target));
            
            #line 136 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugPantheon.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugPantheon_OnClick);
            
            #line default
            #line hidden
            return;
            case 105:
            this.ButtonDebugTutorialUi = ((System.Windows.Controls.Button)(target));
            
            #line 144 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugTutorialUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugTutorialUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 106:
            this.ButtonDebugEssenceTab = ((System.Windows.Controls.Button)(target));
            
            #line 145 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugEssenceTab.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugEssenceTab_OnClick);
            
            #line default
            #line hidden
            return;
            case 107:
            this.ButtonDebugDivinationTab = ((System.Windows.Controls.Button)(target));
            
            #line 146 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugDivinationTab.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugDivinationTab_OnClick);
            
            #line default
            #line hidden
            return;
            case 108:
            this.ButtonDebugCurrencyTab = ((System.Windows.Controls.Button)(target));
            
            #line 147 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugCurrencyTab.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugCurrencyTab_OnClick);
            
            #line default
            #line hidden
            return;
            case 109:
            this.ButtonDebugStashUi = ((System.Windows.Controls.Button)(target));
            
            #line 148 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugStashUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugStashUi_OnClick);
            
            #line default
            #line hidden
            return;
            case 110:
            this.ButtonDebugFragmentTab = ((System.Windows.Controls.Button)(target));
            
            #line 149 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugFragmentTab.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugFragmentTab_Click);
            
            #line default
            #line hidden
            return;
            case 111:
            this.ButtonDebugProphecyPopupUi = ((System.Windows.Controls.Button)(target));
            
            #line 150 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugProphecyPopupUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugProphecyPopupUi_Click);
            
            #line default
            #line hidden
            return;
            case 112:
            this.ButtonDebugBestiary = ((System.Windows.Controls.Button)(target));
            
            #line 151 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugBestiary.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugBestiary_Click);
            
            #line default
            #line hidden
            return;
            case 113:
            this.ButtonDebugShopUi = ((System.Windows.Controls.Button)(target));
            
            #line 152 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugShopUi.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugShopUi_Click);
            
            #line default
            #line hidden
            return;
            case 114:
            this.ButtonDebugIncursion = ((System.Windows.Controls.Button)(target));
            
            #line 153 "..\..\..\..\DumpTab\Gui.xaml"
            this.ButtonDebugIncursion.Click += new System.Windows.RoutedEventHandler(this.ButtonDebugIncursion_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

