#pragma checksum "..\..\..\..\ObjectExplorer\Gui.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "485F251AF235B36674276BDBF6EAC5E50D65020D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Legacy.ObjectExplorer;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Legacy.ObjectExplorer {
    
    
    /// <summary>
    /// Gui
    /// </summary>
    public partial class Gui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 11 "..\..\..\..\ObjectExplorer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition LeftColDefinition;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\..\ObjectExplorer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition SplitterColDefinition;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\..\ObjectExplorer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition RightColDefinition;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\ObjectExplorer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GridSplitter GridSplitter;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\ObjectExplorer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonRefresh;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\ObjectExplorer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TreeView TreeViewObjects;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\ObjectExplorer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonRefreshObject;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\ObjectExplorer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSave;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\ObjectExplorer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl tabControl;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\ObjectExplorer\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxInfoRaw;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Legacy;component/objectexplorer/gui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\ObjectExplorer\Gui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.LeftColDefinition = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 2:
            this.SplitterColDefinition = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 3:
            this.RightColDefinition = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 4:
            this.GridSplitter = ((System.Windows.Controls.GridSplitter)(target));
            return;
            case 5:
            this.ButtonRefresh = ((System.Windows.Controls.Button)(target));
            
            #line 22 "..\..\..\..\ObjectExplorer\Gui.xaml"
            this.ButtonRefresh.Click += new System.Windows.RoutedEventHandler(this.ButtonRefresh_OnClick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.TreeViewObjects = ((System.Windows.Controls.TreeView)(target));
            
            #line 24 "..\..\..\..\ObjectExplorer\Gui.xaml"
            this.TreeViewObjects.SelectedItemChanged += new System.Windows.RoutedPropertyChangedEventHandler<object>(this.TreeViewObjects_OnSelectedItemChanged);
            
            #line default
            #line hidden
            return;
            case 7:
            this.ButtonRefreshObject = ((System.Windows.Controls.Button)(target));
            
            #line 29 "..\..\..\..\ObjectExplorer\Gui.xaml"
            this.ButtonRefreshObject.Click += new System.Windows.RoutedEventHandler(this.ButtonRefreshObject_OnClick);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ButtonSave = ((System.Windows.Controls.Button)(target));
            
            #line 31 "..\..\..\..\ObjectExplorer\Gui.xaml"
            this.ButtonSave.Click += new System.Windows.RoutedEventHandler(this.ButtonSave_OnClick);
            
            #line default
            #line hidden
            return;
            case 9:
            this.tabControl = ((System.Windows.Controls.TabControl)(target));
            return;
            case 10:
            this.TextBoxInfoRaw = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

