#pragma checksum "..\..\..\..\ItemFilterEditor\Gui.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "D034B07CB0FB598B29F62EB5F7D50C1F120EB48F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Legacy.ItemFilterEditor;
using MahApps.Metro.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Legacy.ItemFilterEditor {
    
    
    /// <summary>
    /// Gui
    /// </summary>
    public partial class Gui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 26 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TreeView TreeViewCategories;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridSettings;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CategoryGrid;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ItemFilterGrid;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxDescription;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridTypesNames;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridRarities;
        
        #line default
        #line hidden
        
        
        #line 139 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxRarityNormal;
        
        #line default
        #line hidden
        
        
        #line 145 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxRarityMagic;
        
        #line default
        #line hidden
        
        
        #line 151 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxRarityRare;
        
        #line default
        #line hidden
        
        
        #line 157 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxRarityUnique;
        
        #line default
        #line hidden
        
        
        #line 163 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxRarityQuest;
        
        #line default
        #line hidden
        
        
        #line 169 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxRarityGem;
        
        #line default
        #line hidden
        
        
        #line 175 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxRarityCurrency;
        
        #line default
        #line hidden
        
        
        #line 181 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxRarityProphecy;
        
        #line default
        #line hidden
        
        
        #line 192 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridSocketColors;
        
        #line default
        #line hidden
        
        
        #line 207 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridSocketCount;
        
        #line default
        #line hidden
        
        
        #line 228 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridLinks;
        
        #line default
        #line hidden
        
        
        #line 249 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridSize;
        
        #line default
        #line hidden
        
        
        #line 288 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridItemLevel;
        
        #line default
        #line hidden
        
        
        #line 307 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridQuality;
        
        #line default
        #line hidden
        
        
        #line 328 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridAffixes;
        
        #line default
        #line hidden
        
        
        #line 342 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxIdentifiedEnabled;
        
        #line default
        #line hidden
        
        
        #line 349 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridHighestImplicitValue;
        
        #line default
        #line hidden
        
        
        #line 361 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.UniformGrid GridElderShaper;
        
        #line default
        #line hidden
        
        
        #line 362 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxElderEnabled;
        
        #line default
        #line hidden
        
        
        #line 363 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxShaperEnabled;
        
        #line default
        #line hidden
        
        
        #line 364 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxElderOrShaperEnabled;
        
        #line default
        #line hidden
        
        
        #line 394 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxDebugPickupLimit;
        
        #line default
        #line hidden
        
        
        #line 397 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxLimitWisdomPickup;
        
        #line default
        #line hidden
        
        
        #line 401 "..\..\..\..\ItemFilterEditor\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckBoxLimitPortalPickup;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Legacy;component/itemfiltereditor/gui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TreeViewCategories = ((System.Windows.Controls.TreeView)(target));
            
            #line 27 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.TreeViewCategories.SelectedItemChanged += new System.Windows.RoutedPropertyChangedEventHandler<object>(this.HandleTreeItemChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 53 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.AddCategoryHandler);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 54 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteCategoryHandler);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 55 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.AddFilterHandler);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 58 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteFilterHandler);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 59 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.EnableFilterHandler);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 60 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.DisableFilterHandler);
            
            #line default
            #line hidden
            return;
            case 8:
            this.GridSettings = ((System.Windows.Controls.Grid)(target));
            return;
            case 9:
            this.CategoryGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 10:
            this.ItemFilterGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 11:
            this.TextBoxDescription = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.GridTypesNames = ((System.Windows.Controls.Grid)(target));
            return;
            case 13:
            this.GridRarities = ((System.Windows.Controls.Grid)(target));
            return;
            case 14:
            this.CheckBoxRarityNormal = ((System.Windows.Controls.CheckBox)(target));
            
            #line 141 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityNormal.DataContextChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.HandleRarityDataContextChanged);
            
            #line default
            #line hidden
            
            #line 142 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityNormal.Loaded += new System.Windows.RoutedEventHandler(this.HandleRarityCheckboxLoaded);
            
            #line default
            #line hidden
            
            #line 143 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityNormal.Checked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            
            #line 144 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityNormal.Unchecked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            return;
            case 15:
            this.CheckBoxRarityMagic = ((System.Windows.Controls.CheckBox)(target));
            
            #line 147 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityMagic.DataContextChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.HandleRarityDataContextChanged);
            
            #line default
            #line hidden
            
            #line 148 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityMagic.Loaded += new System.Windows.RoutedEventHandler(this.HandleRarityCheckboxLoaded);
            
            #line default
            #line hidden
            
            #line 149 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityMagic.Checked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            
            #line 150 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityMagic.Unchecked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            return;
            case 16:
            this.CheckBoxRarityRare = ((System.Windows.Controls.CheckBox)(target));
            
            #line 153 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityRare.DataContextChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.HandleRarityDataContextChanged);
            
            #line default
            #line hidden
            
            #line 154 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityRare.Loaded += new System.Windows.RoutedEventHandler(this.HandleRarityCheckboxLoaded);
            
            #line default
            #line hidden
            
            #line 155 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityRare.Checked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            
            #line 156 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityRare.Unchecked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            return;
            case 17:
            this.CheckBoxRarityUnique = ((System.Windows.Controls.CheckBox)(target));
            
            #line 159 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityUnique.DataContextChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.HandleRarityDataContextChanged);
            
            #line default
            #line hidden
            
            #line 160 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityUnique.Loaded += new System.Windows.RoutedEventHandler(this.HandleRarityCheckboxLoaded);
            
            #line default
            #line hidden
            
            #line 161 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityUnique.Checked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            
            #line 162 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityUnique.Unchecked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            return;
            case 18:
            this.CheckBoxRarityQuest = ((System.Windows.Controls.CheckBox)(target));
            
            #line 165 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityQuest.DataContextChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.HandleRarityDataContextChanged);
            
            #line default
            #line hidden
            
            #line 166 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityQuest.Loaded += new System.Windows.RoutedEventHandler(this.HandleRarityCheckboxLoaded);
            
            #line default
            #line hidden
            
            #line 167 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityQuest.Checked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            
            #line 168 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityQuest.Unchecked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            return;
            case 19:
            this.CheckBoxRarityGem = ((System.Windows.Controls.CheckBox)(target));
            
            #line 171 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityGem.DataContextChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.HandleRarityDataContextChanged);
            
            #line default
            #line hidden
            
            #line 172 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityGem.Loaded += new System.Windows.RoutedEventHandler(this.HandleRarityCheckboxLoaded);
            
            #line default
            #line hidden
            
            #line 173 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityGem.Checked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            
            #line 174 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityGem.Unchecked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            return;
            case 20:
            this.CheckBoxRarityCurrency = ((System.Windows.Controls.CheckBox)(target));
            
            #line 177 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityCurrency.DataContextChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.HandleRarityDataContextChanged);
            
            #line default
            #line hidden
            
            #line 178 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityCurrency.Loaded += new System.Windows.RoutedEventHandler(this.HandleRarityCheckboxLoaded);
            
            #line default
            #line hidden
            
            #line 179 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityCurrency.Checked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            
            #line 180 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityCurrency.Unchecked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            return;
            case 21:
            this.CheckBoxRarityProphecy = ((System.Windows.Controls.CheckBox)(target));
            
            #line 183 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityProphecy.DataContextChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.HandleRarityDataContextChanged);
            
            #line default
            #line hidden
            
            #line 184 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityProphecy.Loaded += new System.Windows.RoutedEventHandler(this.HandleRarityCheckboxLoaded);
            
            #line default
            #line hidden
            
            #line 185 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityProphecy.Checked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            
            #line 186 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            this.CheckBoxRarityProphecy.Unchecked += new System.Windows.RoutedEventHandler(this.HandleRarityChanged);
            
            #line default
            #line hidden
            return;
            case 22:
            this.GridSocketColors = ((System.Windows.Controls.Grid)(target));
            return;
            case 23:
            this.GridSocketCount = ((System.Windows.Controls.Grid)(target));
            return;
            case 24:
            this.GridLinks = ((System.Windows.Controls.Grid)(target));
            return;
            case 25:
            this.GridSize = ((System.Windows.Controls.Grid)(target));
            return;
            case 26:
            this.GridItemLevel = ((System.Windows.Controls.Grid)(target));
            return;
            case 27:
            this.GridQuality = ((System.Windows.Controls.Grid)(target));
            return;
            case 28:
            this.GridAffixes = ((System.Windows.Controls.Grid)(target));
            return;
            case 29:
            this.CheckBoxIdentifiedEnabled = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 30:
            this.GridHighestImplicitValue = ((System.Windows.Controls.Grid)(target));
            return;
            case 31:
            this.GridElderShaper = ((System.Windows.Controls.Primitives.UniformGrid)(target));
            return;
            case 32:
            this.CheckBoxElderEnabled = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 33:
            this.CheckBoxShaperEnabled = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 34:
            this.CheckBoxElderOrShaperEnabled = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 35:
            
            #line 374 "..\..\..\..\ItemFilterEditor\Gui.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveButtonClick);
            
            #line default
            #line hidden
            return;
            case 36:
            this.CheckBoxDebugPickupLimit = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 37:
            this.CheckBoxLimitWisdomPickup = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 38:
            this.CheckBoxLimitPortalPickup = ((System.Windows.Controls.CheckBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

