#pragma checksum "..\..\..\..\DevTab\Gui.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "E69A1701431660D509B0A566195FFCACAA0CAB69"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ICSharpCode.AvalonEdit;
using ICSharpCode.AvalonEdit.Editing;
using ICSharpCode.AvalonEdit.Highlighting;
using ICSharpCode.AvalonEdit.Rendering;
using ICSharpCode.AvalonEdit.Search;
using Legacy.DevTab;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Legacy.DevTab {
    
    
    /// <summary>
    /// Gui
    /// </summary>
    public partial class Gui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 22 "..\..\..\..\DevTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal ICSharpCode.AvalonEdit.TextEditor TextBoxCode;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\DevTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxFileName;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\DevTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxClassName;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\DevTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonExecuteText;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\DevTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonExecuteFile;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\DevTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxAssemblies;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\DevTab\Gui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonChooseFile;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Legacy;component/devtab/gui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\DevTab\Gui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TextBoxCode = ((ICSharpCode.AvalonEdit.TextEditor)(target));
            
            #line 25 "..\..\..\..\DevTab\Gui.xaml"
            this.TextBoxCode.LostFocus += new System.Windows.RoutedEventHandler(this.TextBoxCode_OnLostFocus);
            
            #line default
            #line hidden
            return;
            case 2:
            this.TextBoxFileName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.TextBoxClassName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.ButtonExecuteText = ((System.Windows.Controls.Button)(target));
            
            #line 37 "..\..\..\..\DevTab\Gui.xaml"
            this.ButtonExecuteText.Click += new System.Windows.RoutedEventHandler(this.ButtonExecuteText_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ButtonExecuteFile = ((System.Windows.Controls.Button)(target));
            
            #line 40 "..\..\..\..\DevTab\Gui.xaml"
            this.ButtonExecuteFile.Click += new System.Windows.RoutedEventHandler(this.ButtonExecuteFile_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.TextBoxAssemblies = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.ButtonChooseFile = ((System.Windows.Controls.Button)(target));
            
            #line 51 "..\..\..\..\DevTab\Gui.xaml"
            this.ButtonChooseFile.Click += new System.Windows.RoutedEventHandler(this.ButtonChooseFile_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

